# ╔══════════════════════════════════════════════╗
# ║                Configuration                 ║
# ╚══════════════════════════════════════════════╝
spring.application.name=template-maven-library
